allObjs = {
    "Apartment_Block_01", "Apartment_Block_02", "Apartment_Block_03",
    "Barrier",
    "BBQ",
    "Bicycle_01",
    "Books",
    "Bush_01", "Bush_02", "Bush_03", "Bush_04", "Bush_05", "Bush_06", "Bush_07", "Bush_08",
    "Buzz Can",
    "Cactus_01", "Cactus_02",
    "Carpet",
    "Chair_01",
    "Church",
    "Cloud_01", "Cloud_02", "Cloud_03", "Cloud_04", "Cloud_05",
    "Coffee Mug",
    "Coffee Table",
    "Computer_01", "Computer_02",
    "Convertible",
    "Couch",
    "Crates",
    "Crossing Bar01",
    "Cut-out_01", "Cut-out_02", "Cut-out_03", "Cut-out_04", "Cut-out_05", "Cut-out_06", "Cut-out_07", "Cut-out_08",
    "Desk_01", "Desk_02", "Desk_03",
    "Duff Can",
    "Fast Food", "Fast Food.001",
    "Fax",
    "Fence_01", "Fence_02", "Fence_03", "Fence_04", "Fence_05", "Fence_06", "Fence_07",
    "Fire Hydrant",
    "Garbage Bin",
    "Government Building",
    "Grass_01", "Grass_02", "Grass_03",
    "Hair_Mesh.016mesh",
    "Helicopter",
    "Highrise_01", "Highrise_02", "Highrise_03", "Highrise_04",
    "Hot Dog Machine",
    "House_Plant_01", "House_Plant_02", "House_Plant_03", "House_Plant_04", "House_Plant_05",
    "House_01", "House_02", "House_03", "House_04", "House_05", "House_06", "House_07", "House_08", "House_09", "House_10", "House_11", "House_12", "House_13", "House_14",
    "Kwik-E-Mart",
    "Lamp",
    "Lenny_Mesh.001",
    "Luxury Car",
    "Mailbox",
    "Motorbike",
    "Palettes",
    "Pencil",
    "Phone",
    "PhoneBox",
    "Photocopier",
    "Pickup Truck",
    "Plane",
    "Pool",
    "Powerlines_01", "Powerlines_02", "Powerlines_03", "Powerlines_04", "Powerlines_05",
    "Printer",
    "Register",
    "Road_Sign_01", "Road_Sign_02", "Road_Sign_03", "Road_Sign_04", "Road_Sign_05", "Road_Sign_06", "Road_Sign_07", "Road_Sign_08", "Road_Sign_09", "Road_Sign_10",
    "Road_01", "Road_02", "Road_03", "Road_04 (Gradient)",
    "Sabre",
    "School",
    "School Bus",
    "Sedan_01", "Sedan_02", "Sedan_03", "Sedan_04",
    "Shopfront_01", "Shopfront_02", "Shopfront_03", "Shopfront_04", "Shopfront_05", "Shopfront_06", "Shopfront_07", "Shopfront_08",
    "Shotgun",
    "Side Table",
    "Small Plane",
    "Sports Car_01", "Sports Car_02", "Sports Car_04", "Sports Car_04",
    "Squishee Machine",
    "Standing Lamp",
    "Stlye 01_Male_Hair-A", "Stlye 01_Male_Hair-B", "Stlye 01_Male_Shirt", "Stlye 01_Male_Shoes",
    "Streetlight _01", "Streetlight_02", "Streetlight_03", "Streetlight_04",
    "Stump",
    "SUV_01", "SUV_02",
    "Sword",
    "Tank",
    "Torus.001", "Torus.003",
    "Traffic Cone_01", "Traffic Cone_02", "Traffic Cone_03",
    "Traffic Light_01", "Traffic Light_02", "Traffic Light_03", "Traffic Light_04", "Traffic Light_05", "Traffic Light_06", "Traffic Light_07",
    "Train_01",
    "Trashcan_01", "Trashcan_02",
    "Tree_01", "Tree_02", "Tree_03", "Tree_04", "Tree_05", "Tree_06", "Tree_07",
    "Truck_01", "Truck_02",
    "TV",
    "UFO", "UFO_Beam",
    "Van",
    "VCR",
    "Velvet Rope",
    "Vending Machine_01", "Vending Machine_02", "Vending Machine_03", "Vending Machine_04",
    "Wagon_01", "Wagon_01 Windshield", "Wagon_02",
    "Water Tower",
}